---
- name: test login to Arista
  hosts: arista
  gather_facts: false
  connection: local
  tasks:
    - telnet:
        user: admin
        port: 5000
        login_prompt: "localhost login:"
        prompts:
          - "[>|#]"
        command:
          - term length 0
          - enable
          - configure terminal
          - hostname {{inventory_hostname}}
          - end
          - zerotouch disable