---
- name: debug vars
  hosts: arista
  gather_facts: false
  connection: local
  tasks:
    - debug: #var=vars
        msg:
          - "hostname: {{inventory_hostname}}"
          - "console ip:{{console_ip}}"
          - "console_port: {{console_port}}"