---
- name: test login to Arista
  hosts: arista
  gather_facts: false
  connection: local
  tasks:
    - name: Disabling zero touch provisionning
      telnet:
        user: admin
        host: "{{console_ip}}"
        port: "{{console_port}}"
        login_prompt: "localhost login:"
        prompts:
          - "[>|#]"
        command:
          - zerotouch disable