---
- name: configure junos device
  hosts: junos
  gather_facts: false
  connection: netconf
  tasks:
#    - debug: var=vars
#      run_once: true
#      tags: 
#        - debug
    - junos_config:
        lines:
          - set interfaces fxp0 description management-test-2
#          - delete system login user ansible authentication ssh-rsa "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCW7OmoV8AjZiJzTIRRqGAIX1JBh6ERELhMSCmte9iC3Nsl+62oM2fcccjmKuJadrsVjpTu1b5dcEYL0zd1bS9npgCJ/QMwYhmrE/tza+amW2qQuOi51eKQI4hkBXUdJmv9xOiapQ7QX0dvz2zfHB78cWHfzXtckeXmtVwmFrL9GKXVkx7PAic0Zg1hDOzh+OgiSf4KWnZbXmKru/TF+IkiRyeiWpc4vArpusdJkKdWNh1oKxFj6zlSBkNXApihB3o8sF8b7zkEvLOiWItuT0WyJdu3nB21GY+dCBUCENaLr7x2NS11DHLVDYc6XkbMhZjYwKwEy7EeYnK+wMUTUSS5 ansible@xy1-ubu03"
      tags:
        - config