---
networks:
  dc1_p2p:
    main: 10.1.0.0/24
    subnets:
      net_1:
        ip: 10.1.0.0/31
      net_2:
        ip: 10.1.0.2/31
      net_3:
        ip: 10.1.0.4/31
      net_4:
        ip: 10.1.0.6/31
      net_5:
        ip: 10.1.0.8/31
      net_6:
        ip: 10.1.0.10/31
  dc2_p2p:
    main: 10.2.0.0/24
    subnets:
      net_1:
        ip: 10.2.0.0/31
      net_2:
        ip: 10.2.0.2/31
      net_3:
        ip: 10.2.0.4/31
      net_4:
        ip: 10.2.0.6/31
      net_5:
        ip: 10.2.0.8/31
      net_6:
        ip: 10.2.0.10/31
  isp_1:
    internet_1:
      ip: 1.1.1.0/31
    internet_2:
      ip: 1.1.2.0/31
  isp_2:
    internet_1:
      ip: 2.1.1.0/31
    internet_2:
      ip: 2.1.1.2/31